services:
  - type: web
    name: optigreen-chem
    env: docker
    region: ohio
    plan: standard
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "8501"
      - key: PYTHONPATH
        value: "/app/src"
