services:
  - type: web
    name: optigreen-chem
    env: docker
    region: ohio
    plan: standard
    healthCheckPath: /_stcore/health
    envVars:
      - key: PYTHONPATH
        value: "/app/src"
